---
abstract: 'Downgrade listed dependencies to recommendations if present.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  Dist::Zilla::Util::Test::KENTNL: '1.003002'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::DZil: '0'
  Test::More: '0.89'
  Test::Requires: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.047, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-Prereqs-Soften
provides:
  Dist::Zilla::Plugin::Prereqs::Soften:
    file: lib/Dist/Zilla/Plugin/Prereqs/Soften.pm
    version: '0.006002'
recommends:
  Moose: '2.000'
  strict: '0'
  warnings: '0'
requires:
  Dist::Zilla::Role::PrereqSource: '0'
  Dist::Zilla::Util::ConfigDumper: '0'
  Moose: '0'
  Moose::Util::TypeConstraints: '0'
  MooseX::Types::Moose: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/kentnl/Dist-Zilla-Plugin-Prereqs-Soften/issues
  homepage: https://github.com/kentnl/Dist-Zilla-Plugin-Prereqs-Soften
  repository: https://github.com/kentnl/Dist-Zilla-Plugin-Prereqs-Soften.git
version: '0.006002'
